services:
  subscriptions:
    container_name: subscriptions-prod
    image: fusecons.azurecr.io/fuse-subscriptions:latest
    environment:
      GO_ENV: production
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - backend_fuse-network
networks:
  backend_fuse-network:
    external: true
