ALTER TABLE IF EXISTS subscriptions DROP COLUMN is_deleted;
ALTER TABLE IF EXISTS subscriptions ALTER COLUMN user_id SET NOT NULL;

ALTER TABLE IF EXISTS refunds DROP COLUMN is_deleted;
ALTER TABLE IF EXISTS refunds ALTER COLUMN user_id SET NOT NULL;