services:
  inapp:
    image: fusecons.azurecr.io/fuse-workers-notifications-inapp:latest
    container_name: inapp-notifications-worker
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    networks:
      - notifications_notifications-network

networks:
  notifications_notifications-network:
    external: true
