services:
  inapp:
    image: fusecons.azurecr.io/inapp-notifications-worker:latest
    container_name: inapp-notifications-worker
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - notifications_notifications-network

networks:
  notifications_notifications-network:
    external: true
