/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSubscriptionRouteImport } from './routes/app/subscription'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppRoomsRouteImport } from './routes/app/rooms'
import { Route as AppRoomRouteImport } from './routes/app/room'
import { Route as AuthCallbackIndexRouteImport } from './routes/auth/callback/index'
import { Route as AppSubscriptionIndexRouteImport } from './routes/app/subscription/index'
import { Route as AppRoomIndexRouteImport } from './routes/app/room/index'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomRoute = AppRoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackIndexRoute = AuthCallbackIndexRouteImport.update({
  id: '/auth/callback/',
  path: '/auth/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubscriptionIndexRoute = AppSubscriptionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSubscriptionRoute,
} as any)
const AppRoomIndexRoute = AppRoomIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoomRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/room': typeof AppRoomRouteWithChildren
  '/app/rooms': typeof AppRoomsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/room/': typeof AppRoomIndexRoute
  '/app/subscription/': typeof AppSubscriptionIndexRoute
  '/auth/callback': typeof AuthCallbackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/rooms': typeof AppRoomsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/room': typeof AppRoomIndexRoute
  '/app/subscription': typeof AppSubscriptionIndexRoute
  '/auth/callback': typeof AuthCallbackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/room': typeof AppRoomRouteWithChildren
  '/app/rooms': typeof AppRoomsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/room/': typeof AppRoomIndexRoute
  '/app/subscription/': typeof AppSubscriptionIndexRoute
  '/auth/callback/': typeof AuthCallbackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/room'
    | '/app/rooms'
    | '/app/settings'
    | '/app/subscription'
    | '/app/'
    | '/app/room/'
    | '/app/subscription/'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/rooms'
    | '/app/settings'
    | '/app'
    | '/app/room'
    | '/app/subscription'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/room'
    | '/app/rooms'
    | '/app/settings'
    | '/app/subscription'
    | '/app/'
    | '/app/room/'
    | '/app/subscription/'
    | '/auth/callback/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthCallbackIndexRoute: typeof AuthCallbackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rooms': {
      id: '/app/rooms'
      path: '/rooms'
      fullPath: '/app/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/room': {
      id: '/app/room'
      path: '/room'
      fullPath: '/app/room'
      preLoaderRoute: typeof AppRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback/': {
      id: '/auth/callback/'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/subscription/': {
      id: '/app/subscription/'
      path: '/'
      fullPath: '/app/subscription/'
      preLoaderRoute: typeof AppSubscriptionIndexRouteImport
      parentRoute: typeof AppSubscriptionRoute
    }
    '/app/room/': {
      id: '/app/room/'
      path: '/'
      fullPath: '/app/room/'
      preLoaderRoute: typeof AppRoomIndexRouteImport
      parentRoute: typeof AppRoomRoute
    }
  }
}

interface AppRoomRouteChildren {
  AppRoomIndexRoute: typeof AppRoomIndexRoute
}

const AppRoomRouteChildren: AppRoomRouteChildren = {
  AppRoomIndexRoute: AppRoomIndexRoute,
}

const AppRoomRouteWithChildren =
  AppRoomRoute._addFileChildren(AppRoomRouteChildren)

interface AppSubscriptionRouteChildren {
  AppSubscriptionIndexRoute: typeof AppSubscriptionIndexRoute
}

const AppSubscriptionRouteChildren: AppSubscriptionRouteChildren = {
  AppSubscriptionIndexRoute: AppSubscriptionIndexRoute,
}

const AppSubscriptionRouteWithChildren = AppSubscriptionRoute._addFileChildren(
  AppSubscriptionRouteChildren,
)

interface AppRouteChildren {
  AppRoomRoute: typeof AppRoomRouteWithChildren
  AppRoomsRoute: typeof AppRoomsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppRoomRoute: AppRoomRouteWithChildren,
  AppRoomsRoute: AppRoomsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionRoute: AppSubscriptionRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthCallbackIndexRoute: AuthCallbackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
