// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Subscription struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	PlanID            pgtype.UUID
	PlanType          string
	PurchaseDate      pgtype.Timestamptz
	ValidUntil        pgtype.Timestamptz
	RazorpayPaymentID string
	RazorpayOrderID   string
	RazorpaySignature string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type SubscriptionUsage struct {
	ID             pgtype.UUID
	SubscriptionID pgtype.UUID
	UserID         pgtype.UUID
	ValidFrom      pgtype.Timestamptz
	ValidUntil     pgtype.Timestamptz
	Usage          []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
