// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refunds.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNewRefund = `-- name: CreateNewRefund :one
INSERT INTO refunds (subscription_id, razorpay_payment_id, amount, user_id)
VALUES ($1, $2, $3, $4)
RETURNING (id, subscription_id, razorpay_payment_id, amount, created_at, updated_at)
`

type CreateNewRefundParams struct {
	SubscriptionID    pgtype.UUID
	RazorpayPaymentID string
	Amount            pgtype.Numeric
	UserID            pgtype.UUID
}

func (q *Queries) CreateNewRefund(ctx context.Context, arg CreateNewRefundParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, createNewRefund,
		arg.SubscriptionID,
		arg.RazorpayPaymentID,
		arg.Amount,
		arg.UserID,
	)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const getRefundByPaymentID = `-- name: GetRefundByPaymentID :one
SELECT id, subscription_id, razorpay_payment_id, amount, created_at, updated_at
FROM refunds WHERE razorpay_payment_id = $1
`

type GetRefundByPaymentIDRow struct {
	ID                pgtype.UUID
	SubscriptionID    pgtype.UUID
	RazorpayPaymentID string
	Amount            pgtype.Numeric
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetRefundByPaymentID(ctx context.Context, razorpayPaymentID string) (GetRefundByPaymentIDRow, error) {
	row := q.db.QueryRow(ctx, getRefundByPaymentID, razorpayPaymentID)
	var i GetRefundByPaymentIDRow
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.RazorpayPaymentID,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefundsByUserID = `-- name: GetRefundsByUserID :many
SELECT id, subscription_id, razorpay_payment_id, amount, created_at, updated_at
FROM refunds WHERE user_id = $1 ORDER BY created_at DESC
`

type GetRefundsByUserIDRow struct {
	ID                pgtype.UUID
	SubscriptionID    pgtype.UUID
	RazorpayPaymentID string
	Amount            pgtype.Numeric
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetRefundsByUserID(ctx context.Context, userID pgtype.UUID) ([]GetRefundsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getRefundsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRefundsByUserIDRow
	for rows.Next() {
		var i GetRefundsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.RazorpayPaymentID,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
