// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (user_id, plan_id, plan_type, purchase_date, valid_until, razorpay_payment_id, razorpay_order_id, razorpay_signature)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING (id, plan_id, plan_type, purchase_date, valid_until, razorpay_payment_id, razorpay_order_id, razorpay_signature)
`

type CreateSubscriptionParams struct {
	UserID            pgtype.UUID
	PlanID            pgtype.UUID
	PlanType          string
	PurchaseDate      pgtype.Timestamptz
	ValidUntil        pgtype.Timestamptz
	RazorpayPaymentID string
	RazorpayOrderID   string
	RazorpaySignature string
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.PlanID,
		arg.PlanType,
		arg.PurchaseDate,
		arg.ValidUntil,
		arg.RazorpayPaymentID,
		arg.RazorpayOrderID,
		arg.RazorpaySignature,
	)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const getAllSubscriptions = `-- name: GetAllSubscriptions :many
SELECT id, user_id, plan_id, plan_type, purchase_date, valid_until, razorpay_payment_id, razorpay_order_id, razorpay_signature
FROM subscriptions WHERE user_id = $1 ORDER BY created_at DESC
`

type GetAllSubscriptionsRow struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	PlanID            pgtype.UUID
	PlanType          string
	PurchaseDate      pgtype.Timestamptz
	ValidUntil        pgtype.Timestamptz
	RazorpayPaymentID string
	RazorpayOrderID   string
	RazorpaySignature string
}

func (q *Queries) GetAllSubscriptions(ctx context.Context, userID pgtype.UUID) ([]GetAllSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, getAllSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSubscriptionsRow
	for rows.Next() {
		var i GetAllSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.PlanType,
			&i.PurchaseDate,
			&i.ValidUntil,
			&i.RazorpayPaymentID,
			&i.RazorpayOrderID,
			&i.RazorpaySignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, user_id, plan_id, plan_type, purchase_date, valid_until, razorpay_payment_id, razorpay_order_id, razorpay_signature
FROM subscriptions WHERE id = $1 ORDER BY created_at DESC LIMIT 1
`

type GetSubscriptionByIDRow struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	PlanID            pgtype.UUID
	PlanType          string
	PurchaseDate      pgtype.Timestamptz
	ValidUntil        pgtype.Timestamptz
	RazorpayPaymentID string
	RazorpayOrderID   string
	RazorpaySignature string
}

func (q *Queries) GetSubscriptionByID(ctx context.Context, id pgtype.UUID) (GetSubscriptionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i GetSubscriptionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.PlanType,
		&i.PurchaseDate,
		&i.ValidUntil,
		&i.RazorpayPaymentID,
		&i.RazorpayOrderID,
		&i.RazorpaySignature,
	)
	return i, err
}

const getSubscriptionByUserID = `-- name: GetSubscriptionByUserID :one
SELECT id, user_id, plan_id, plan_type, purchase_date, valid_until, razorpay_payment_id, razorpay_order_id, razorpay_signature
FROM subscriptions WHERE user_id = $1 ORDER BY created_at DESC LIMIT 1
`

type GetSubscriptionByUserIDRow struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	PlanID            pgtype.UUID
	PlanType          string
	PurchaseDate      pgtype.Timestamptz
	ValidUntil        pgtype.Timestamptz
	RazorpayPaymentID string
	RazorpayOrderID   string
	RazorpaySignature string
}

func (q *Queries) GetSubscriptionByUserID(ctx context.Context, userID pgtype.UUID) (GetSubscriptionByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByUserID, userID)
	var i GetSubscriptionByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.PlanType,
		&i.PurchaseDate,
		&i.ValidUntil,
		&i.RazorpayPaymentID,
		&i.RazorpayOrderID,
		&i.RazorpaySignature,
	)
	return i, err
}
